version: '3.8'

services:
  shopme-admin:
    build: ./shopme-admin
    ports:
      - '${ADMIN_EXTERNAL_PORT}:80'
    restart: unless-stopped
    networks:
      - shopme-network
    mem_limit: 500m

  shopme-client:
    build: ./shopme-client
    ports:
      - '${CLIENT_EXTERNAL_PORT}:80'
    restart: unless-stopped
    networks:
      - shopme-network
    mem_limit: 500m

networks:
  shopme-network:
    driver: bridge
